on:
  push:
    branches-ignore:
      - gh-pages
      - main

name: quarto

jobs:
  quarto:
    runs-on: ubuntu-24.04
    name: check-package
    env:
      RSPM: "https://packagemanager.posit.co/cran/__linux__/noble/latest"
      QUARTO_SOURCE: "source"
      QUARTO_OUTPUT: "output"
    permissions:
      contents: read
    steps:
      - name: "Prepare quarto"
        uses: inbo/actions/quarto_prepare@composite
        with:
          path: ${{ env.QUARTO_SOURCE }}
          texlive: array babel-dutch babel-french babel-german booktabs caption colortbl datetime2 emptypage enumitem etoolbox fancyhdr fontawesome5 footmisc geometry hyphen-dutch hyphen-french hyphen-german hyperref iftex lastpage longtable makecell multirow parskip pdfpages selnolig setspace textcase titlesec tocloft ucharcat unicode-math url xcolor xurl
      - name: "Render quarto"
        uses: inbo/actions/quarto_render@composite
        with:
          path: ${{ env.QUARTO_SOURCE }}
          output: ${{ env.QUARTO_OUTPUT }}

   publish:
    name: deploy-gh-pages
    runs-on: ubuntu-24.04
    needs: quarto
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: "Deploy gh-pages"
        uses: inbo/actions/quarto_publish@composite
